services:
  - type: worker
    name: sam-telegram-bot
    env: python
    plan: starter

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      python main.py

    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GAME_API_URL
        sync: false
      - key: SRD_SERVICE_URL
        sync: false
      - key: ADMIN_TELEGRAM_ID
        sync: false
      - key: LOG_LEVEL
        sync: false
      - key: HTTP_TIMEOUT
        sync: false
